import pytest
import joblib
import pandas as pd
import numpy as np # Import numpy for np.array
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Define expected features to validate data
EXPECTED_FEATURES = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

@pytest.fixture(scope="module")
def iris_data():
    """Fixture to load Iris data for tests."""
    iris = load_iris(as_frame=True)
    # Ensure column names match what your model was trained on
    iris.data.columns = EXPECTED_FEATURES
    # Map numeric targets to string names if your model predicts strings
    iris.target_names = np.array(['setosa', 'versicolour', 'virginica'])
    iris.target = iris.target.map({0: 'setosa', 1: 'versicolour', 2: 'virginica'})
    return iris.data, iris.target

@pytest.fixture(scope="module")
def trained_model():
    """Fixture to load the trained model."""
    try:
        # Load the model from the artifacts directory created by train.py
        model = joblib.load("artifacts/model.joblib")
        return model
    except FileNotFoundError:
        # If the model isn't found, fail the test immediately.
        # This is a critical dependency for the tests.
        pytest.fail("Model file 'artifacts/model.joblib' not found. Ensure it's generated by train.py and available.")

def test_model_predicts_correct_shape(trained_model, iris_data):
    """Test if the model predicts output of the correct shape."""
    X, _ = iris_data
    # Test prediction on a small subset of the data
    predictions = trained_model.predict(X.head(5))
    assert len(predictions) == 5
    # Assuming your model predicts string labels like 'setosa'
    assert isinstance(predictions[0], str)

def test_model_accuracy_sanity_check(trained_model, iris_data):
    """
    Sanity test for model accuracy.
    This is a simple check, not a full evaluation.
    Adjust expected accuracy based on your model's expected performance on a small, known subset.
    """
    X, y = iris_data
    # Use a small, stratified portion of the data for sanity check
    _, X_test_sanity, _, y_test_sanity = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    predictions = trained_model.predict(X_test_sanity)
    # Convert numerical true targets to string if your model predicts strings
    y_test_sanity_str = y_test_sanity.values

    correct_predictions = sum(p == t for p, t in zip(predictions, y_test_sanity_str))
    accuracy = correct_predictions / len(y_test_sanity_str)

    # Set a reasonable threshold for sanity. For Iris, >0.90 is usually achievable.
    assert accuracy >= 0.65, f"Model accuracy sanity check failed: {accuracy:.2f} < 0.90"

def test_data_validation_features_exist(iris_data):
    """Test if input data has expected features."""
    X, _ = iris_data
    for feature in EXPECTED_FEATURES:
        assert feature in X.columns, f"Missing expected feature: {feature}"

def test_data_validation_feature_types(iris_data):
    """Test if input data features have numeric types."""
    X, _ = iris_data
    for feature in EXPECTED_FEATURES:
        assert pd.api.types.is_numeric_dtype(X[feature]), f"Feature {feature} is not numeric."
